#!/bin/bash

if [[ $# -ne 1 ]]
then
    echo Specify time >&2
    exit 1
fi

TITLE='Task Timer'
TIME_LEN=$1

notify_message() {
    local left=$1
    local msg=$2
    echo "$(date --iso-8601=seconds) $msg"
    if [[ $(( $left % $TIME_LEN )) -eq 0 ]]
    then
        osascript -e 'display notification "'"$msg"'" with title "'"$TITLE"'"'
    fi
}

for left in $(seq $TIME_LEN -1 1)
do
    notify_message $left "$left minutes left"
    sleep 60
done

notify_message 0 "Time is up"
